### PR TITLE
Set main process to fix standardized node import

### PR DESCRIPTION
**Pull request by PatricNox**
Should probably solve https://github.com/vestusola/vue-chat-emoji/issues/6

### CODE REVIEW

**Comment by PatricNox** [comment]
Please do make a new release once possible! 😄

**Comment by vestusola** [comment]
> Please do make a new release once possible! 😄

Will do that.

**Comment by vestusola** [comment]
Is the typescript issue solved #7 ?

**Comment by PatricNox** [comment]
> Is the typescript issue solved #7 ?

Not as of yet, that one requires some more work

**Pull request merged**
